/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package org.emftext.language.BON.resource.bon.grammar;

public class BonGrammarInformationProvider {
	
	public final static org.eclipse.emf.ecore.EStructuralFeature ANONYMOUS_FEATURE = org.eclipse.emf.ecore.EcoreFactory.eINSTANCE.createEAttribute();
	static {
		ANONYMOUS_FEATURE.setName("_");
	}
	
	public final static BonGrammarInformationProvider INSTANCE = new BonGrammarInformationProvider();
	
	private java.util.Set<String> keywords;
	
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_0_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getInformal_charts().getEStructuralFeature(org.emftext.language.BON.BONPackage.INFORMAL_CHARTS__SYSTEM_CHART), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getSystem_chart(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_0_0_0_1_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getInformal_charts().getEStructuralFeature(org.emftext.language.BON.BONPackage.INFORMAL_CHARTS__CLUSTER_CHARTS), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getCluster_chart(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_0_0_0_1_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_0_0_0_1_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_0_0_0_1_0_1_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getInformal_charts().getEStructuralFeature(org.emftext.language.BON.BONPackage.INFORMAL_CHARTS__CLASS_CHARTS), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getClass_chart(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_0_0_0_1_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_0_0_0_1_0_1_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_0_0_0_1_0_2_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getInformal_charts().getEStructuralFeature(org.emftext.language.BON.BONPackage.INFORMAL_CHARTS__EVENT_CHARTS), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getEvent_chart(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_0_0_0_1_0_2 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_0_0_0_1_0_2_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_0_0_0_1_0_3_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getInformal_charts().getEStructuralFeature(org.emftext.language.BON.BONPackage.INFORMAL_CHARTS__SCENARIO_CHARTS), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getScenario_chart(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_0_0_0_1_0_3 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_0_0_0_1_0_3_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_0_0_0_1_0_4_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getInformal_charts().getEStructuralFeature(org.emftext.language.BON.BONPackage.INFORMAL_CHARTS__CREATION_CHARTS), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getCreation_chart(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_0_0_0_1_0_4 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_0_0_0_1_0_4_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_0_0_0_1_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_0_0_0_1_0_0, BON_0_0_0_1_0_1, BON_0_0_0_1_0_2, BON_0_0_0_1_0_3, BON_0_0_0_1_0_4);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_0_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_0_0_0_1_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.STAR);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_0_0_0_0, BON_0_0_0_1);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_0 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getInformal_charts(), BON_0_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_1_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("system_chart", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_1_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getSystem_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.SYSTEM_CHART__NAME), "IDENTIFIER", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_1_0_0_2_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getSystem_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.SYSTEM_CHART__CHART_INDEXING), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getIndexing(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_1_0_0_2_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_1_0_0_2_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_1_0_0_2_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_1_0_0_2_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_1_0_0_2 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_1_0_0_2_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_1_0_0_3_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getSystem_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.SYSTEM_CHART__EXPLANATION), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getExplanation(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_1_0_0_3_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_1_0_0_3_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_1_0_0_3_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_1_0_0_3_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_1_0_0_3 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_1_0_0_3_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_1_0_0_4_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getSystem_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.SYSTEM_CHART__CHART_PART), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getPart(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_1_0_0_4_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_1_0_0_4_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_1_0_0_4_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_1_0_0_4_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_1_0_0_4 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_1_0_0_4_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_1_0_0_5 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getSystem_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.SYSTEM_CHART__CLUSTER_ENTRIES), org.emftext.language.BON.resource.bon.grammar.BonCardinality.STAR, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getCluster(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_1_0_0_6 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("end", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_1_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_1_0_0_0, BON_1_0_0_1, BON_1_0_0_2, BON_1_0_0_3, BON_1_0_0_4, BON_1_0_0_5, BON_1_0_0_6);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_1_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_1_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_1 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getSystem_chart(), BON_1_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_2_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("explanation", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_2_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getExplanation().getEStructuralFeature(org.emftext.language.BON.BONPackage.EXPLANATION__NAME), "MANIFEST_TEXTBLOCK", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_2_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_2_0_0_0, BON_2_0_0_1);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_2_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_2_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_2 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getExplanation(), BON_2_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_3_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("indexing", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_3_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getIndexing().getEStructuralFeature(org.emftext.language.BON.BONPackage.INDEXING__INDEX_TERM_LIST), org.emftext.language.BON.resource.bon.grammar.BonCardinality.PLUS, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getIndex_Identifier(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_3_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_3_0_0_0, BON_3_0_0_1);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_3_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_3_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_3 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getIndexing(), BON_3_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_4_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("part", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_4_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getPart().getEStructuralFeature(org.emftext.language.BON.BONPackage.PART__NAME), "MANIFEST_TEXTBLOCK", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_4_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_4_0_0_0, BON_4_0_0_1);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_4_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_4_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_4 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getPart(), BON_4_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_5_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getIndex_Identifier().getEStructuralFeature(org.emftext.language.BON.BONPackage.INDEX_IDENTIFIER__NAME), "FEATURE_IDENTIFIER", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_5_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword(":", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_5_0_0_2 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getIndex_Identifier().getEStructuralFeature(org.emftext.language.BON.BONPackage.INDEX_IDENTIFIER__INDEX_STRING), "MANIFEST_TEXTBLOCK", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_5_0_0_3_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword(",", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_5_0_0_3_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getIndex_Identifier().getEStructuralFeature(org.emftext.language.BON.BONPackage.INDEX_IDENTIFIER__INDEX_STRING), "MANIFEST_TEXTBLOCK", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_5_0_0_3_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_5_0_0_3_0_0_0, BON_5_0_0_3_0_0_1);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_5_0_0_3_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_5_0_0_3_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_5_0_0_3 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_5_0_0_3_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.STAR);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_5_0_0_4 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword(";", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_5_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_5_0_0_0, BON_5_0_0_1, BON_5_0_0_2, BON_5_0_0_3, BON_5_0_0_4);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_5_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_5_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_5 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getIndex_Identifier(), BON_5_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_6_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("cluster", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_6_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getCluster().getEStructuralFeature(org.emftext.language.BON.BONPackage.CLUSTER__NAME), "IDENTIFIER", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_6_0_0_2 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("description", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_6_0_0_3 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getCluster().getEStructuralFeature(org.emftext.language.BON.BONPackage.CLUSTER__DESCRIPTION), "MANIFEST_TEXTBLOCK", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_6_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_6_0_0_0, BON_6_0_0_1, BON_6_0_0_2, BON_6_0_0_3);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_6_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_6_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_6 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getCluster(), BON_6_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_7_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("cluster_chart", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_7_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getCluster_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CLUSTER_CHART__CLUSTER), "IDENTIFIER", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_7_0_0_2_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getCluster_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CLUSTER_CHART__CHART_INDEXING), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getIndexing(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_7_0_0_2_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_7_0_0_2_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_7_0_0_2_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_7_0_0_2_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_7_0_0_2 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_7_0_0_2_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_7_0_0_3_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getCluster_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CLUSTER_CHART__EXPLANATION), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getExplanation(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_7_0_0_3_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_7_0_0_3_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_7_0_0_3_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_7_0_0_3_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_7_0_0_3 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_7_0_0_3_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_7_0_0_4_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getCluster_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CLUSTER_CHART__CHART_PART), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getPart(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_7_0_0_4_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_7_0_0_4_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_7_0_0_4_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_7_0_0_4_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_7_0_0_4 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_7_0_0_4_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_7_0_0_5_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getCluster_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CLUSTER_CHART__CLASS_ENTRIES), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getClassBON(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_7_0_0_5_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_7_0_0_5_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_7_0_0_5_0_1_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getCluster_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CLUSTER_CHART__CLUSTERCHART_ENTRIES), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getCluster(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_7_0_0_5_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_7_0_0_5_0_1_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_7_0_0_5_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_7_0_0_5_0_0, BON_7_0_0_5_0_1);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_7_0_0_5 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_7_0_0_5_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.STAR);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_7_0_0_6 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("end", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_7_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_7_0_0_0, BON_7_0_0_1, BON_7_0_0_2, BON_7_0_0_3, BON_7_0_0_4, BON_7_0_0_5, BON_7_0_0_6);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_7_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_7_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_7 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getCluster_chart(), BON_7_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_8_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("class", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_8_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getClassBON().getEStructuralFeature(org.emftext.language.BON.BONPackage.CLASS_BON__NAME), "IDENTIFIER", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_8_0_0_2 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("description", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_8_0_0_3 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getClassBON().getEStructuralFeature(org.emftext.language.BON.BONPackage.CLASS_BON__DESCRIPTION), "MANIFEST_TEXTBLOCK", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_8_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_8_0_0_0, BON_8_0_0_1, BON_8_0_0_2, BON_8_0_0_3);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_8_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_8_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_8 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getClassBON(), BON_8_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_9_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("class_chart", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_9_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getClass_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CLASS_CHART__CLASS), "IDENTIFIER", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_9_0_0_2_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getClass_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CLASS_CHART__CHART_INDEXING), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getIndexing(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_9_0_0_2_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_9_0_0_2_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_9_0_0_2_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_9_0_0_2_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_9_0_0_2 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_9_0_0_2_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_9_0_0_3_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getClass_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CLASS_CHART__EXPLANATION), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getExplanation(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_9_0_0_3_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_9_0_0_3_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_9_0_0_3_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_9_0_0_3_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_9_0_0_3 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_9_0_0_3_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_9_0_0_4_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getClass_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CLASS_CHART__CHART_PART), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getPart(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_9_0_0_4_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_9_0_0_4_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_9_0_0_4_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_9_0_0_4_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_9_0_0_4 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_9_0_0_4_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_9_0_0_5_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("inherit", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_9_0_0_5_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getClass_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CLASS_CHART__INHERIT), "IDENTIFIER", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_9_0_0_5_0_0_2_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword(",", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_9_0_0_5_0_0_2_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getClass_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CLASS_CHART__INHERIT), "IDENTIFIER", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_9_0_0_5_0_0_2_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_9_0_0_5_0_0_2_0_0_0, BON_9_0_0_5_0_0_2_0_0_1);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_9_0_0_5_0_0_2_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_9_0_0_5_0_0_2_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_9_0_0_5_0_0_2 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_9_0_0_5_0_0_2_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.STAR);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_9_0_0_5_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_9_0_0_5_0_0_0, BON_9_0_0_5_0_0_1, BON_9_0_0_5_0_0_2);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_9_0_0_5_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_9_0_0_5_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_9_0_0_5 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_9_0_0_5_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.STAR);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_9_0_0_6 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getClass_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CLASS_CHART__QUERIES), org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getQueries(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_9_0_0_7 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getClass_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CLASS_CHART__COMMANDS), org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getCommands(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_9_0_0_8 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getClass_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CLASS_CHART__CONSTRAINTS), org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getConstraints(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_9_0_0_9 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("end", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_9_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_9_0_0_0, BON_9_0_0_1, BON_9_0_0_2, BON_9_0_0_3, BON_9_0_0_4, BON_9_0_0_5, BON_9_0_0_6, BON_9_0_0_7, BON_9_0_0_8, BON_9_0_0_9);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_9_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_9_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_9 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getClass_chart(), BON_9_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_10_0_0_0_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("query", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_10_0_0_0_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getQueries().getEStructuralFeature(org.emftext.language.BON.BONPackage.QUERIES__QUERY), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getQuery(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_10_0_0_0_0_0_2_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword(",", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_10_0_0_0_0_0_2_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getQueries().getEStructuralFeature(org.emftext.language.BON.BONPackage.QUERIES__QUERY), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getQuery(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_10_0_0_0_0_0_2_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_10_0_0_0_0_0_2_0_0_0, BON_10_0_0_0_0_0_2_0_0_1);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_10_0_0_0_0_0_2_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_10_0_0_0_0_0_2_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_10_0_0_0_0_0_2 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_10_0_0_0_0_0_2_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.STAR);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_10_0_0_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_10_0_0_0_0_0_0, BON_10_0_0_0_0_0_1, BON_10_0_0_0_0_0_2);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_10_0_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_10_0_0_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_10_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_10_0_0_0_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.STAR);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_10_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_10_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_10_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_10_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_10 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getQueries(), BON_10_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_11_0_0_0_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("command", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_11_0_0_0_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getCommands().getEStructuralFeature(org.emftext.language.BON.BONPackage.COMMANDS__COMMAND), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getCommand(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_11_0_0_0_0_0_2_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword(",", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_11_0_0_0_0_0_2_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getCommands().getEStructuralFeature(org.emftext.language.BON.BONPackage.COMMANDS__COMMAND), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getCommand(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_11_0_0_0_0_0_2_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_11_0_0_0_0_0_2_0_0_0, BON_11_0_0_0_0_0_2_0_0_1);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_11_0_0_0_0_0_2_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_11_0_0_0_0_0_2_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_11_0_0_0_0_0_2 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_11_0_0_0_0_0_2_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.STAR);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_11_0_0_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_11_0_0_0_0_0_0, BON_11_0_0_0_0_0_1, BON_11_0_0_0_0_0_2);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_11_0_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_11_0_0_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_11_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_11_0_0_0_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.STAR);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_11_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_11_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_11_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_11_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_11 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getCommands(), BON_11_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_12_0_0_0_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("constraint", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_12_0_0_0_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getConstraints().getEStructuralFeature(org.emftext.language.BON.BONPackage.CONSTRAINTS__CONSTRAINT), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getConstraint(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_12_0_0_0_0_0_2_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword(",", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_12_0_0_0_0_0_2_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getConstraints().getEStructuralFeature(org.emftext.language.BON.BONPackage.CONSTRAINTS__CONSTRAINT), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getConstraint(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_12_0_0_0_0_0_2_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_12_0_0_0_0_0_2_0_0_0, BON_12_0_0_0_0_0_2_0_0_1);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_12_0_0_0_0_0_2_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_12_0_0_0_0_0_2_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_12_0_0_0_0_0_2 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_12_0_0_0_0_0_2_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.STAR);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_12_0_0_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_12_0_0_0_0_0_0, BON_12_0_0_0_0_0_1, BON_12_0_0_0_0_0_2);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_12_0_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_12_0_0_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_12_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_12_0_0_0_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.STAR);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_12_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_12_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_12_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_12_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_12 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getConstraints(), BON_12_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_13_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getQuery().getEStructuralFeature(org.emftext.language.BON.BONPackage.QUERY__NAME), "MANIFEST_TEXTBLOCK", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_13_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_13_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_13_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_13_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_13 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getQuery(), BON_13_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_14_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getCommand().getEStructuralFeature(org.emftext.language.BON.BONPackage.COMMAND__NAME), "MANIFEST_TEXTBLOCK", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_14_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_14_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_14_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_14_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_14 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getCommand(), BON_14_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_15_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getConstraint().getEStructuralFeature(org.emftext.language.BON.BONPackage.CONSTRAINT__NAME), "MANIFEST_TEXTBLOCK", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_15_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_15_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_15_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_15_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_15 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getConstraint(), BON_15_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_16_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("event_chart", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_16_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getEvent_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.EVENT_CHART__SYSTEM_NAME), "IDENTIFIER", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_16_0_0_2 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getEvent_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.EVENT_CHART__EVENT_TYPE), "EVENTTYPE", org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_16_0_0_3_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getEvent_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.EVENT_CHART__CHART_INDEXING), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getIndexing(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_16_0_0_3_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_16_0_0_3_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_16_0_0_3_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_16_0_0_3_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_16_0_0_3 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_16_0_0_3_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_16_0_0_4_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getEvent_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.EVENT_CHART__EXPLANATION), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getExplanation(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_16_0_0_4_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_16_0_0_4_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_16_0_0_4_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_16_0_0_4_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_16_0_0_4 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_16_0_0_4_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_16_0_0_5_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getEvent_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.EVENT_CHART__CHART_PART), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getPart(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_16_0_0_5_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_16_0_0_5_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_16_0_0_5_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_16_0_0_5_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_16_0_0_5 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_16_0_0_5_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_16_0_0_6 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getEvent_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.EVENT_CHART__EVENT_ENTRIES), org.emftext.language.BON.resource.bon.grammar.BonCardinality.STAR, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getEvent(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_16_0_0_7 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("end", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_16_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_16_0_0_0, BON_16_0_0_1, BON_16_0_0_2, BON_16_0_0_3, BON_16_0_0_4, BON_16_0_0_5, BON_16_0_0_6, BON_16_0_0_7);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_16_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_16_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_16 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getEvent_chart(), BON_16_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_17_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("event", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_17_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getEvent().getEStructuralFeature(org.emftext.language.BON.BONPackage.EVENT__NAME), "MANIFEST_TEXTBLOCK", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_17_0_0_2 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("involves", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_17_0_0_3 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getEvent().getEStructuralFeature(org.emftext.language.BON.BONPackage.EVENT__INVOLVES), "IDENTIFIER", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_17_0_0_4_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword(",", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_17_0_0_4_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getEvent().getEStructuralFeature(org.emftext.language.BON.BONPackage.EVENT__INVOLVES), "IDENTIFIER", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_17_0_0_4_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_17_0_0_4_0_0_0, BON_17_0_0_4_0_0_1);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_17_0_0_4_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_17_0_0_4_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_17_0_0_4 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_17_0_0_4_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.STAR);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_17_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_17_0_0_0, BON_17_0_0_1, BON_17_0_0_2, BON_17_0_0_3, BON_17_0_0_4);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_17_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_17_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_17 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getEvent(), BON_17_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_18_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("scenario_chart", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_18_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getScenario_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.SCENARIO_CHART__SYSTEM_NAME), "IDENTIFIER", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_18_0_0_2_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getScenario_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.SCENARIO_CHART__CHART_INDEXING), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getIndexing(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_18_0_0_2_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_18_0_0_2_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_18_0_0_2_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_18_0_0_2_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_18_0_0_2 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_18_0_0_2_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_18_0_0_3_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getScenario_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.SCENARIO_CHART__EXPLANATION), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getExplanation(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_18_0_0_3_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_18_0_0_3_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_18_0_0_3_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_18_0_0_3_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_18_0_0_3 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_18_0_0_3_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_18_0_0_4_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getScenario_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.SCENARIO_CHART__CHART_PART), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getPart(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_18_0_0_4_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_18_0_0_4_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_18_0_0_4_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_18_0_0_4_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_18_0_0_4 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_18_0_0_4_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_18_0_0_5 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getScenario_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.SCENARIO_CHART__SCENARIO_ENTRIES), org.emftext.language.BON.resource.bon.grammar.BonCardinality.STAR, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getScenario(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_18_0_0_6 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("end", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_18_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_18_0_0_0, BON_18_0_0_1, BON_18_0_0_2, BON_18_0_0_3, BON_18_0_0_4, BON_18_0_0_5, BON_18_0_0_6);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_18_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_18_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_18 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getScenario_chart(), BON_18_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_19_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("scenario", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_19_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getScenario().getEStructuralFeature(org.emftext.language.BON.BONPackage.SCENARIO__NAME), "MANIFEST_TEXTBLOCK", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_19_0_0_2 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("description", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_19_0_0_3 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getScenario().getEStructuralFeature(org.emftext.language.BON.BONPackage.SCENARIO__DESCRIPTION), "MANIFEST_TEXTBLOCK", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_19_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_19_0_0_0, BON_19_0_0_1, BON_19_0_0_2, BON_19_0_0_3);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_19_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_19_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_19 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getScenario(), BON_19_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_20_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("creation_chart", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_20_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getCreation_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CREATION_CHART__SYSTEM_NAME), "IDENTIFIER", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_20_0_0_2_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getCreation_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CREATION_CHART__CHART_INDEXING), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getIndexing(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_20_0_0_2_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_20_0_0_2_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_20_0_0_2_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_20_0_0_2_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_20_0_0_2 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_20_0_0_2_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_20_0_0_3_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getCreation_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CREATION_CHART__EXPLANATION), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getExplanation(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_20_0_0_3_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_20_0_0_3_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_20_0_0_3_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_20_0_0_3_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_20_0_0_3 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_20_0_0_3_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_20_0_0_4_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getCreation_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CREATION_CHART__CHART_PART), org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getPart(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_20_0_0_4_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_20_0_0_4_0_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_20_0_0_4_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_20_0_0_4_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_20_0_0_4 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_20_0_0_4_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.QUESTIONMARK);
	public final static org.emftext.language.BON.resource.bon.grammar.BonContainment BON_20_0_0_5 = new org.emftext.language.BON.resource.bon.grammar.BonContainment(org.emftext.language.BON.BONPackage.eINSTANCE.getCreation_chart().getEStructuralFeature(org.emftext.language.BON.BONPackage.CREATION_CHART__CREATION_ENTRIES), org.emftext.language.BON.resource.bon.grammar.BonCardinality.STAR, new org.eclipse.emf.ecore.EClass[] {org.emftext.language.BON.BONPackage.eINSTANCE.getCreation(), }, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_20_0_0_6 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("end", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_20_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_20_0_0_0, BON_20_0_0_1, BON_20_0_0_2, BON_20_0_0_3, BON_20_0_0_4, BON_20_0_0_5, BON_20_0_0_6);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_20_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_20_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_20 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getCreation_chart(), BON_20_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_21_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("creator", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_21_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getCreation().getEStructuralFeature(org.emftext.language.BON.BONPackage.CREATION__CREATOR), "IDENTIFIER", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_21_0_0_2 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword("creates", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_21_0_0_3 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getCreation().getEStructuralFeature(org.emftext.language.BON.BONPackage.CREATION__CREATES), "IDENTIFIER", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonKeyword BON_21_0_0_4_0_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonKeyword(",", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	public final static org.emftext.language.BON.resource.bon.grammar.BonPlaceholder BON_21_0_0_4_0_0_1 = new org.emftext.language.BON.resource.bon.grammar.BonPlaceholder(org.emftext.language.BON.BONPackage.eINSTANCE.getCreation().getEStructuralFeature(org.emftext.language.BON.BONPackage.CREATION__CREATES), "IDENTIFIER", org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, 0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_21_0_0_4_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_21_0_0_4_0_0_0, BON_21_0_0_4_0_0_1);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_21_0_0_4_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_21_0_0_4_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonCompound BON_21_0_0_4 = new org.emftext.language.BON.resource.bon.grammar.BonCompound(BON_21_0_0_4_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.STAR);
	public final static org.emftext.language.BON.resource.bon.grammar.BonSequence BON_21_0_0 = new org.emftext.language.BON.resource.bon.grammar.BonSequence(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_21_0_0_0, BON_21_0_0_1, BON_21_0_0_2, BON_21_0_0_3, BON_21_0_0_4);
	public final static org.emftext.language.BON.resource.bon.grammar.BonChoice BON_21_0 = new org.emftext.language.BON.resource.bon.grammar.BonChoice(org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE, BON_21_0_0);
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule BON_21 = new org.emftext.language.BON.resource.bon.grammar.BonRule(org.emftext.language.BON.BONPackage.eINSTANCE.getCreation(), BON_21_0, org.emftext.language.BON.resource.bon.grammar.BonCardinality.ONE);
	
	public static String getSyntaxElementID(org.emftext.language.BON.resource.bon.grammar.BonSyntaxElement syntaxElement) {
		if (syntaxElement == null) {
			// null indicates EOF
			return "<EOF>";
		}
		for (java.lang.reflect.Field field : org.emftext.language.BON.resource.bon.grammar.BonGrammarInformationProvider.class.getFields()) {
			Object fieldValue;
			try {
				fieldValue = field.get(null);
				if (fieldValue == syntaxElement) {
					String id = field.getName();
					return id;
				}
			} catch (Exception e) { }
		}
		return null;
	}
	
	public static org.emftext.language.BON.resource.bon.grammar.BonSyntaxElement getSyntaxElementByID(String syntaxElementID) {
		try {
			return (org.emftext.language.BON.resource.bon.grammar.BonSyntaxElement) org.emftext.language.BON.resource.bon.grammar.BonGrammarInformationProvider.class.getField(syntaxElementID).get(null);
		} catch (Exception e) {
			return null;
		}
	}
	
	public final static org.emftext.language.BON.resource.bon.grammar.BonRule[] RULES = new org.emftext.language.BON.resource.bon.grammar.BonRule[] {
		BON_0,
		BON_1,
		BON_2,
		BON_3,
		BON_4,
		BON_5,
		BON_6,
		BON_7,
		BON_8,
		BON_9,
		BON_10,
		BON_11,
		BON_12,
		BON_13,
		BON_14,
		BON_15,
		BON_16,
		BON_17,
		BON_18,
		BON_19,
		BON_20,
		BON_21,
	};
	
	/**
	 * Returns all keywords of the grammar. This includes all literals for boolean and
	 * enumeration terminals.
	 */
	public java.util.Set<String> getKeywords() {
		if (this.keywords == null) {
			this.keywords = new java.util.LinkedHashSet<String>();
			for (org.emftext.language.BON.resource.bon.grammar.BonRule rule : RULES) {
				findKeywords(rule, this.keywords);
			}
		}
		return keywords;
	}
	
	/**
	 * Finds all keywords in the given element and its children and adds them to the
	 * set. This includes all literals for boolean and enumeration terminals.
	 */
	private void findKeywords(org.emftext.language.BON.resource.bon.grammar.BonSyntaxElement element, java.util.Set<String> keywords) {
		if (element instanceof org.emftext.language.BON.resource.bon.grammar.BonKeyword) {
			keywords.add(((org.emftext.language.BON.resource.bon.grammar.BonKeyword) element).getValue());
		} else if (element instanceof org.emftext.language.BON.resource.bon.grammar.BonBooleanTerminal) {
			keywords.add(((org.emftext.language.BON.resource.bon.grammar.BonBooleanTerminal) element).getTrueLiteral());
			keywords.add(((org.emftext.language.BON.resource.bon.grammar.BonBooleanTerminal) element).getFalseLiteral());
		} else if (element instanceof org.emftext.language.BON.resource.bon.grammar.BonEnumerationTerminal) {
			org.emftext.language.BON.resource.bon.grammar.BonEnumerationTerminal terminal = (org.emftext.language.BON.resource.bon.grammar.BonEnumerationTerminal) element;
			for (String key : terminal.getLiteralMapping().keySet()) {
				keywords.add(key);
			}
		}
		for (org.emftext.language.BON.resource.bon.grammar.BonSyntaxElement child : element.getChildren()) {
			findKeywords(child, this.keywords);
		}
	}
	
}
